language: node_js
node_js:
- '6'
deploy:
  provider: npm
  on:
    tags: true
    repo: theme-tools/sass-tools
  email:
    secure: nH1NmXV8I5CDs1fLNj0keVrT4E++SXqvAzQLzCVcio5l0SV+jqtalTA2iGzBTCcZFo4RvLbTMBGmszvId3ZrVr84LN/WL/YBux5bm+PuBz25HLXgG8Ib5TK1xciPn1KrXi+SkcSqf/pHMtimjU3gO17+NZ5nRHvB5edOLI6jx1hAhYoKiAvFaSZMYabnFE8aXPGJssMwiHEp+WNePhpkjBgECWXG5DcnO92QzIhNuEsNZR93JFOmeeKe83JJuR//Hm98fCbwgMxXpGkibZvXNDNygggy2ATyULHxrVBkFVi59oR/2jLqiJoqAO/cD7gJcRXQWkNJXcEBGE39H0i7UO41iyHsk1HWTNiwx6RJNuv7UdJt+PISjTwCJRZja3IYMuxLPDJoYWxejxQfa5W3MI/5UAcnWJKO22HHQ/W9v7xtbkCIq+LRbg+MuuibHJtdWa08w9YqSVeVLYACnHqPoallZ8/MccLlLXGYmowGJ0IgthmkvPDRsaOg1hsMEowT4OcB1EbuusLRnSjhmpEIEQKdfAqbULOqFfvvfP0E7IpLZ+rBW3f57NK9spUuQsYtvTNOKoKELsO4YtC7qre26ila0hTa7M7jfuWFoIhNA+ipEThJTikQfmxuJe0fHpLZ8DwDanaYA4K2GF9O05fROEk8QdTJj8435hNqIk65u9c=
  api_key:
      secure: MoTJy3hmNwbGhdPk0vLRdAIkXNoqhwIzEpcisEVK3XJ+hDW6jRZcT0a5I72hG92vIqobT9zkIi7howUCRYfAypIHeBJCoonSf/dRxGGvETktEdWowYXqngfqxPXnvxTbGe2VgfViRo+SRcwwsZPRo+HibQGiFiPGzG64T3hppaP2sbKVyZeyu7viIwifePQo37DpGMyYs+sl67INqNpWb/LMPTQrukPvKyLhldc7lT0FdUaV1/2oKgtPqv67nd2wTdWZ9D7qY5xmQMk/SkeMAn1HMmFUx4CwF03gsoQIUQHOC6HQaN6XlMf7a45LVV9XhC/KDIhqsZgrloY8wISSTqIq10c2l9jOtTS4XPuxjhCcBj3uh4+ZU3hYX2a8+FvEsX+CB43tCxMIWsyA9u4n0+IR8RrEOtFC8lMEotwgsy2K6ObgGg8OTPxWdeMxI5kjhjCh1yvSNwstQwSu+L3YLBunyqj3QkDjbpPS7oSxw+VwgUpQHak8GfQ73hIQPl2Vk1F4pfwxZhBmXk5KKUGl8jyFVidqgQcAA3069Rc/84+h3We+IThGgc3P4LhgroKQuyfjX3P/GTK5a1GtFFGrzSBYUKdphQOypvpbID+IUFyXHoci9GknV4F+4rSHsrtX+Nv6zb/j2VUrPzIWjnZpHGJsOwHD3lNxPAnJ4xIYEMs=
notifications:
  email:
    on_success: never
