language: node_js
node_js:
- '4.2'
- '6'
- node
deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: nH1NmXV8I5CDs1fLNj0keVrT4E++SXqvAzQLzCVcio5l0SV+jqtalTA2iGzBTCcZFo4RvLbTMBGmszvId3ZrVr84LN/WL/YBux5bm+PuBz25HLXgG8Ib5TK1xciPn1KrXi+SkcSqf/pHMtimjU3gO17+NZ5nRHvB5edOLI6jx1hAhYoKiAvFaSZMYabnFE8aXPGJssMwiHEp+WNePhpkjBgECWXG5DcnO92QzIhNuEsNZR93JFOmeeKe83JJuR//Hm98fCbwgMxXpGkibZvXNDNygggy2ATyULHxrVBkFVi59oR/2jLqiJoqAO/cD7gJcRXQWkNJXcEBGE39H0i7UO41iyHsk1HWTNiwx6RJNuv7UdJt+PISjTwCJRZja3IYMuxLPDJoYWxejxQfa5W3MI/5UAcnWJKO22HHQ/W9v7xtbkCIq+LRbg+MuuibHJtdWa08w9YqSVeVLYACnHqPoallZ8/MccLlLXGYmowGJ0IgthmkvPDRsaOg1hsMEowT4OcB1EbuusLRnSjhmpEIEQKdfAqbULOqFfvvfP0E7IpLZ+rBW3f57NK9spUuQsYtvTNOKoKELsO4YtC7qre26ila0hTa7M7jfuWFoIhNA+ipEThJTikQfmxuJe0fHpLZ8DwDanaYA4K2GF9O05fROEk8QdTJj8435hNqIk65u9c=
  api_key:
    secure: UUeG7bxj9foehkvR064q3zNnHjBillNsBSaUiuKLPL/hsrngJObkDhNOGd1Ob/LnuJskkvPVHpE/yfbfXaKKZuniWcfX4HTJyAD8m1WVFLASpd6WYFS7kl14sEKupxf6cIycy/Jib+2kcx7xim3DTCx3VjLoF82QlrLvYtG1qT48kNbtnxhcgWgabirAUC1j+IXlY9gV/jsHlgIguxjcOXUiva4qm/G4zkRVSwCsh1xogbVA2xMlVLSYBbJtZvF5ff0UdN2FNrsKPBxgul+aSCt0+gPMaDCpYnXR6VkffczZPhD6WP8ZIfIlGkYWJaFzVsYNBvk62SwIe2t/KhRc5NOLILt5+ALPM2kDXvRsEoZsUtrwar/85idOJUK45x9grXVfWidQRHS3OCZK2AbHjyK3ko0zqzL1FugyQk+AsMxds7XBrYCY9tjn1WBelsZA2rWHmqKf3esT57f3IweVYgCDCAwShKvXiHHw9ztKJnd6tA0cINDZd3efSyncG+xebJX2ZYwRUMcZgEi4c2ftiX3VTWXgkjx3v5wTR0igHsW1TsgUl+ml7U6Oq0srrEpWmct6MBQYvotKeDhzQs/YXkymVXB9iSMJFV+V3OLKdd9fcn9/6y9U4Uz8DabrAYBr2fq3i9eJFQLml6UYMBO3neqbXH7tdZXGpdcg307I4FQ=
notifications:
  email:
    on_success: never
